plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "14"
    checks:
      squid:S1068:
        enabled: false # Unused fields. Since we use lombok, the check results so many false positives
      squid:S00112:
        enabled: false # Use of generic exceptions in method declaration.
      squid:S1214:
        enabled: false # Use constants in interfaces

  pmd:
    enabled: true
    checks:
      AtLeastOneConstructor:
        enabled: false # Since we use lombok, it's not actual
      LawOfDemeter:
        enabled: false # We love Java Stream API and other chaining-friendly libraries!
      JUnitTestsShouldIncludeAssert:
        enabled: false # Spring Boot tests use the underlying statements inside its own
      BeanMembersShouldSerialize:
        enabled: false # Most of the declared beans in our app should not be serialized
      UseProperClassLoader:
        enabled: false
      CommentDefaultAccessModifier:
        enabled: false
      SignatureDeclareThrowsException:
        enabled: false
      ExcessiveImports:
        enabled: false
      DefaultPackage:
        enabled: false # Lombok-associated issue
      CallSuperInConstructor:
        enabled: false
      DataflowAnomalyAnalysis:
        enabled: false
      OnlyOneReturn:
        enabled: false
      ConstantsInInterface:
        enabled: false
      AvoidInstantiatingObjectsInLoops:
        enabled: false

    config:
      file: pmd.xml

  checkstyle:
    enabled: true
    config:
      file: checkstyle.xml
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false # We separate static imports from usual ones but this check does not expect that and thus warns
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocParagraphCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false

checks:
  argument-count:
    config:
      threshold: 100
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 550
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 55
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50

exclude_patterns:
  - "/web/**"
  - "/api/src/test/**"
