plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "14"

  pmd:
    enabled: true
    checks:
      AtLeastOneConstructor:
        enabled: false
      LawOfDemeter:
        enabled: false
      JUnitTestsShouldIncludeAssert:
        enabled: false
      BeanMembersShouldSerialize:
        enabled: false
    config:
      rules:
        - "category/java/bestpractices.xml"
        - "category/java/codestyle.xml"
        - "category/java/design.xml"
        - "category/java/errorprone.xml"
        - "category/java/multithreading.xml"
        - "category/java/performance.xml"
        - "category/java/security.xml"

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50

exclude_patterns:
  - "/web/**"
