version: '3'
services:
  web:
    build: web
    expose:
      - 80
    depends_on:
      - api
    ports:
      - "80:80"
  api:
#    build: api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accula
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
