version: '3'
services:
  web:
#    image: docker.pkg.github.com/accula/accula/accula_web:latest
    build: web
    expose:
      - 80
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://64.225.96.225
  api:
#    image: docker.pkg.github.com/accula/accula/accula_api:latest
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - API_URL=http://64.225.96.225
      - WEB_URL=http://64.225.96.225
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=accula
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accula
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
