version: '3'
services:
  web:
    build: web
    expose:
      - 80
    ports:
      - "80:80"
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accula
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
