version: '3'
services:
  web:
    build: web
    expose:
      - 80
      - 443
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      args:
        - GPR_USERNAME=
        - GPR_TOKEN=
    depends_on:
      - postgres
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MinRAMPercentage=30 -XX:MaxRAMPercentage=90
      - PORT=8080
      - API_URL=
      - WEB_URL=
      - WEBHOOK_URL=
      - WEBHOOK_SECRET=
      - WEBHOOK_SSL_ENABLED=false
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=accula
      - REPOS_PATH=/app/repos/
      - JWT_SIGNATURE_PUBLIC_KEY=/app/keys/accula-public.der
      - JWT_SIGNATURE_PRIVATE_KEY=/app/keys/accula-private.der
      - ROLE_ROOT=10428179,15687094,28392375,665821
      - ROLE_ADMIN=
    volumes:
      - ./repos:/app/repos
      - ./keys:/app/keys
  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accula
    command: postgres -c 'max_connections=200' -c 'shared_buffers=1GB'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
