spring:
  profiles:
    include:
      - secrets

  flyway:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,repo,write:repo_hook
            redirect-uri: ${API_URL}/api/login/github/callback

  codec:
    max-in-memory-size: 10MB

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

accula:
  jwt:
    signature:
      publicKey: ${JWT_SIGNATURE_PUBLIC_KEY}
      privateKey: ${JWT_SIGNATURE_PRIVATE_KEY}
    issuer: accula
    expiresIn:
      access: 1m
      refresh: 90d
    refreshTokenEndpointPath: /api/refreshToken

  cluster:
    webUrl: ${WEB_URL}

  db:
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASS}
    database: ${DB_NAME}

    pool:
      maxIdleTime: 1m
      minSize: 10
      maxSize: 195

  reposPath: ${REPOS_PATH}

  webhook:
    url: ${WEBHOOK_URL}/api/webhook
    secret: ${WEBHOOK_SECRET}
    ssl-enabled: ${WEBHOOK_SSL_ENABLED}

  code:
    lines:
      cache: 500
